import Navbar from "@/components/Navbar";
import SessionWrapper from "@/components/SessionWrapper";
import type { Metadata } from "next";
import { Toaster } from "react-hot-toast";
import "./globals.css";


export const metadata: Metadata = {
  title: "IntraQ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
        >
        <SessionWrapper>
          <Navbar/>
        <Toaster/>
        {children}
      </SessionWrapper>
      </body>
    </html>
  );
}
